apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: northwind-api
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - skaffold/local.yaml