apiVersion: v1
kind: Service
metadata:
  name: northwind-api-lb
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: http
    targetPort: http
  selector:
    lfda-app-name: northwind-api

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: northwind-api
spec:
  replicas: 1
  selector:
    matchLabels:
      lfda-app-name: northwind-api
  template:
    metadata:
      labels:
        lfda-app-name: northwind-api
    spec:
      containers:
        - name: northwind-api
          image: gcr.io/cloud-solutions-images/gceme:1.0.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_HOST
              value: api-db-mariadb.mariadb 
            - name: NORTHWIND_DB_DATABASE
              value: "northwind"
            - name: NORTHWIND_DB_USER
              value: root
            - name: NORTHWIND_DB_PASSWORD
              value: lfda
            - name: AUTHO_URL
              value: "https://dev-uq9rrgqz.auth0.com"
            - name: AUTHO_AUDIENCE
              value: "http://192.168.39.190:30101"
            - name: AUTHO_CLIENT_ID
              value: "KS8dbjVr6LzJEtWsIuLPl4TRmSgXiOqi"
            - name: AUTHO_CLIENT_SECRET
              value: "Qyy3FgF4xYJfRHU5TQt2ckYj2B0fLY5Rbz-FjvyGJQiptLO8PKuUjqqFyAlJKPdh" 
