apiVersion: v1
kind: Pod
metadata:
  name: northwind-api
  labels:    
    cf-app-name: northwind-api
spec:
  containers:
  - name: northwind-api
    image: northwind-api
    ports:
    - containerPort: 3000
      name: http    